### PR TITLE
bump github.com/dgrijalva/jwt-go v3.2.0

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/dgrijalva/jwt-go/compare/a2c85815a77d0f951e33ba4db5ae93629a1530af...06ea1031745cb8b3dab3f6a236daf2b0aa468b7e

### CODE REVIEW

**Comment by thaJeztah** [comment]
hm.. looks like there's no CI in this repository 🤔

**Comment by thaJeztah** [comment]
Right, looks like changes are needed for this;

```
--- FAIL: TestPanic1 (0.00s)
        Error Trace:    error_test.go:191
        Error:		"[/Users/sebastiaan/go/src/github.com/docker/licensing/lib/errors/panic1_test.go:14 /usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 /Users/sebastiaan/go/src/github.com/docker/licensing/lib/errors/panic1_test.go:24 /Users/sebastiaan/go/src/github.com/docker/licensing/lib/errors/panic1_test.go:20 /Users/sebastiaan/go/src/github.com/docker/licensing/lib/errors/panic1_test.go:16 /Users/sebastiaan/go/src/github.com/docker/licensing/lib/errors/error_test.go:185 /usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:865 /usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337]" should have 9 item(s), but has 8
```

**Comment by thaJeztah** [comment]
hm; master is failing on the same error; might be that it's not working on Go 1.12?

**Comment by thaJeztah** [comment]
opened https://github.com/docker/licensing/pull/26 to fix the test

**Comment by thaJeztah** [comment]
Rebased, but looks like this needs changes to work;

```
# github.com/docker/licensing/lib/go-auth/jwt
lib/go-auth/jwt/jwt.go:91:14: invalid operation: token.Claims[username] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:92:14: invalid operation: token.Claims[email] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:95:14: invalid operation: token.Claims[sub] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:98:15: invalid operation: token.Claims[scope] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:105:14: invalid operation: token.Claims[jti] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:107:14: invalid operation: token.Claims[iat] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:108:14: invalid operation: token.Claims[exp] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:111:15: invalid operation: token.Claims[sessionid] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:112:15: invalid operation: token.Claims[userid] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:129:31: invalid operation: token.Claims[username] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:129:31: too many errors
FAIL	github.com/docker/licensing [build failed]
# github.com/docker/licensing/lib/go-auth/jwt [github.com/docker/licensing/lib/go-auth/jwt.test]
lib/go-auth/jwt/jwt.go:91: invalid operation: token.Claims[username] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:92: invalid operation: token.Claims[email] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:95: invalid operation: token.Claims[sub] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:98: invalid operation: token.Claims[scope] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:105: invalid operation: token.Claims[jti] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:107: invalid operation: token.Claims[iat] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:108: invalid operation: token.Claims[exp] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:111: invalid operation: token.Claims[sessionid] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:112: invalid operation: token.Claims[userid] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:129: invalid operation: token.Claims[username] (type jwt.Claims does not support indexing)
lib/go-auth/jwt/jwt.go:129: too many errors
```

**Comment by guillaumerose** [comment]
Oh I didn't saw your PR @thaJeztah when I opened this one: https://github.com/docker/licensing/pull/27

**Comment by thaJeztah** [comment]
@guillaumerose oh, no problem: perfect! If you can add `closes #25` to your PR description, then this one will close once that's merged 👍

**Pull request closed without merging**
